user:
  length:
    max_name: 50
    min_pass: 6
    max_email: 50
category:
  length:
    max_name: 50
course:
  length:
    max_name: 50
lession:
  length:
    max_name: 50
  page: 30
image:
  size: 400
  capacity: 5
data:
  pages: 20
question:
  answer_default: 1
number:
  zero: 0
  one: 1
  one_float: 1.0
  enought_to_pass: 0.8
