user:
  length:
    max_name: 50
    min_pass: 6
    max_email: 50
answer:
  length:
    max_content: 50
category:
  length:
    max_name: 50
    max_des: 200
course:
  length:
    max_name: 50
    max_des: 200
lesson:
  page: 30
  length:
    max_name: 50
    max_des: 200
question:
  length:
    max_content: 200
    max_meaning: 200
image:
  size: 400
  capacity: 5
data:
  pages: 8
number:
  zero: 0
  one: 1
  two: 2
  one_float: 1.0
  enought_to_pass: 0.8
  four: 4
time:
  format1: "%H:%M:%S"
  format: "%m/%d/%Y - %H:%M"
status_unlearn: "unlearned"
status_learn: "learned"
max_time: 60
table:
  status:
    s0: "warning"
    s1: "active"
    s2: "success"
    s3: "danger"
github: "https://github.com/tatdat97dhbkhn/e_learning"
class_css:
  active: "active"
